### PR TITLE
Update project buildscripts and migrate to MC 1.20.4

### PR DESCRIPTION
**Pull request by braulio-dev**

### CODE REVIEW

**Comment by braulio-dev** [comment]
Currently waiting for an Ignite version compatible with MC 1.20.4. Might have to fork Ignite again

**Comment by braulio-dev** [comment]
`Enchantment.registerEnchantment` has since been removed and support for registering enchantments has been dropped. Need an alternative to register `GlowEnchant`

**Comment by Mykindos** [comment]
> `Enchantment.registerEnchantment` has since been removed and support for registering enchantments has been dropped. Need an alternative to register `GlowEnchant`

Could be done by just adding a useless enchantment to said item instead. Theres probably other ways to make items glow as well without the need of an enchantment

**Comment by braulio-dev** [comment]
Fixes #272

**Review by Mykindos — APPROVED** [review]

**Review by Mykindos — APPROVED** [review]

**Pull request merged**
