### PR TITLE
Fix bows consuming an arrow when fired

### LINKED ISSUE #968: Shooting a bow as a non assassin/ranger will consume the arrow, but not fire
https://discord.com/channels/161738857136521217/1265937620995936317/1265937620995936317
The shot is correctly cancelled, but the arrow is still consumed.

### PR DESCRIPTION
**Pull request by StudentAlleg**
by adding back an arrow when event is cancelled
Fixes #968 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have tested my changes.

### CODE REVIEW

**Comment by braulio-dev** [comment]
I'd rather wait for [this](https://github.com/PaperMC/Paper/pull/9949) than give players the consumable back upon firing. This is a duplication bug waiting to happen.

**Comment by 8SIXSect** [comment]
I think you should leave it as a feature. Maybe add a message saying that we're keeping the arrow or something. It's a punishment for being stupid.

**Review by Mykindos — APPROVED** [review]

**Comment by Mykindos** [comment]
Approved but I agree with what Rey says, this is a dupe waiting to happen if they fix it in a future version

**Comment by StudentAlleg** [comment]
> Approved but I agree with what Rey says, this is a dupe waiting to happen if they fix it in a future version
> 
> Sure its just an arrow dupe, but dupe is a dupe

Can hold off, and if it doesn't get fixed, can include it.

**Pull request closed without merging**
