### PR TITLE
Consumables

### PR DESCRIPTION
**Pull request by ezrn**
## Describe your changes
- New Rabbit Stew, gives Speed I for 7 seconds, 15 second cooldown
- New Suspicious Stew, gives random effect at a random level from 1-4 for 5.0 seconds, 10 second cooldown

- Pending CustomModelData for each of these new items

## Checklist before requesting a review
- [X] I have performed a self-review of my code
- [X] I have tested my changes.

### CODE REVIEW

**Review by Mykindos — CHANGES_REQUESTED** [review]
remove water bottle stuff (its removed)

and make a new .sql file, e.g. V5__Add_new_consumables.sql

**Comment by ezrn** [comment]
> remove water bottle stuff (its removed)
> 
> and make a new .sql file, e.g. V5__Add_new_consumables.sql

you don't want it returned to what it used to be where it helped remove fire?

**Comment by Mykindos** [comment]
> > remove water bottle stuff (its removed)
> > and make a new .sql file, e.g. V5__Add_new_consumables.sql
> 
> you don't want it returned to what it used to be where it helped remove fire?

Not for now, will re-assess if its needed later

I don't want fire based builds to be completely countered by an item

**Comment by ezrn** [comment]
> remove water bottle stuff (its removed)
> 
> and make a new .sql file, e.g. V5__Add_new_consumables.sql

Do you just want me to make the file? Where should I put it and also should I move the added consumables to this file?

**Pull request merged**
